version: "3"

services:
  spark-runtime:
      build:
          context: .
          dockerfile: develop.Dockerfile
      container_name: develop
      volumes:
          - .:/data
      env_file:
        - ./config.env
      command: /bin/sh -c "jupyter lab --ip='0.0.0.0' --port=8888 --NotebookApp.token='' --no-browser --allow-root"
      ports:
      - 8888:8888

  flask_app:
      container_name: flask_app
      restart: unless-stopped
      env_file:
          - ./config.env
      build:
          context: .
          dockerfile: flask_app.Dockerfile
      ports:
          - 5000:5000
      volumes:
          - .:/data